import * as vscode from 'vscode';
import * as fs from 'fs';
import { exec } from 'child_process';

// cleans temp files generated by bundle, such as schema-*.json and *_variables.tf.json
function clean () {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders || workspaceFolders.length === 0) {
    vscode.window.showErrorMessage('No workspace folder opened.');
    return;
  }
  const firstWorkspaceFolder = workspaceFolders[0];
  const currentDir = firstWorkspaceFolder.uri.fsPath;

  if (fs.existsSync(currentDir + '/massdriver.yaml')) {
    exec(`cd ${currentDir} && rm -rf schema-*.json src/*_variables.tf.json src/.terraform*`, (err: Error | null) => {
      if (err) {
        console.error(`exec error: ${err}`);
      } else {
        vscode.window.showInformationMessage('Bundle cleaned of temporary files.');
      }
    });
  } else if (fs.existsSync(currentDir + '/../massdriver.yaml')) {
    exec(`cd ${currentDir} && rm -rf ../schema-*.json *_variables.tf.json .terraform*`, (err: Error | null) => {
      if (err) {
        console.error(`exec error: ${err}`);
      } else {
        vscode.window.showInformationMessage('Bundle cleaned of temporary files.');
      }
    });
  } else {
    vscode.window.showErrorMessage('massdriver.yaml not found in current directory');
  }
}

export { 
  clean,
};